package com.example.rentalcars.model.enums;

public enum PuckUpAndDropOffLocation {
    Blagoevgrad,
    Burgas,
    Dobrich,
    Gabrovo,
    Haskovo,
    Kardzhali,
    Kyustendil,
    Lovech,
    Montana,
    Pazardzhik,
    Pernik,
    Pleven,
    Plovdiv,
    Razgrad,
    Ruse,
    Shumen,
    Silistra,
    Sliven,
    Smolyan,
    Sofia ,
    Stara_Zagora,
    Targovishte,
    Varna,
    Veliko_Tarnovo,
    Vidin,
    Vratsa,
    Yambol
}
